# Generated by Django 5.2.17 on 2026-08-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_remove_cohort_students_alter_cohort_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='cohort',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cohort',
            old_name='is_active',
            new_name='is_open',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='is_published',
        ),
        migrations.AddField(
            model_name='cohort',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
