# Generated by Django 5.2.17 on 2026-08-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_alter_cohort_options_and_more'),
        ('courses', '0003_lessonprogress_program_remove_module_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='courses.program'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
