# Generated by Django 5.2.17 on 2026-08-28 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_cohort_program_cohort_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cohort',
            name='registration_deadline',
            field=models.DateField(),
        ),
    ]
