# Generated by Django 5.2.17 on 2026-08-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_alter_cohort_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
