# Generated by Django 5.2.17 on 2026-08-28 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0006_alter_cohort_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Seminar Room', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('zoom_link', models.URLField(blank=True)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_room', to='cohorts.cohort')),
            ],
        ),
    ]
