# Generated by Django 5.2.17 on 2026-08-28 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0007_seminarroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='cohorts.seminarroom')),
            ],
        ),
    ]
