# Generated by Django 5.2.17 on 2026-08-28 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_seminarresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('question', 'Question'), ('idea', 'Idea'), ('announcement', 'Announcement')], default='question', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_discussions', to=settings.AUTH_USER_MODEL)),
                ('seminar_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='cohorts.seminarroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
