# Generated by Django 5.2.17 on 2026-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
