# Generated by Django 5.2.17 on 2026-08-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
    ]
