# Generated by Django 5.2.17 on 2026-08-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0011_week'),
        ('courses', '0007_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cohorts.week'),
        ),
    ]
