# Generated by Django 5.2.17 on 2026-08-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_module_week'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module_order_per_program',
        ),
    ]
