# Generated by Django 5.2.17 on 2026-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_module_unique_module_order_per_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
    ]
