# Generated by Django 5.2.17 on 2026-08-29 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_announcement'),
        ('projects', '0003_project_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cohorts.cohort'),
        ),
    ]
