# Generated by Django 5.2.17 on 2026-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
