# Generated by Django 5.2.17 on 2026-08-28 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_alter_cohort_options_and_more'),
        ('courses', '0003_lessonprogress_program_remove_module_course_and_more'),
        ('enrollments', '0002_alter_enrollment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course_cohort',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.program'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'program', 'cohort'), name='unique_student_course_cohort'),
        ),
    ]
