# Generated by Django 5.2.17 on 2026-08-28 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0006_alter_cohort_end_date_and_more'),
        ('enrollments', '0003_remove_enrollment_unique_student_course_cohort_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course_cohort',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='program',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'cohort'), name='unique_student_cohort'),
        ),
    ]
