# Generated by Django 5.2.17 on 2026-09-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_remove_enrollment_unique_student_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
